### ISSUE TITLE
投稿第三期

### ISSUE THREAD

**Issue by icodeu** [jikexueyuanwiki/geek-weekly-newsletter#4]
写自己的开源库，发布到 JitPack.io

https://github.com/icodeu/HelloLibrary

推荐理由：这是你成为Android开源贡献者的第一步

**Comment by icodeu** [comment]
这是 干货集，可是我在右侧加不了lable

**Comment by wenquan0hf** [comment]
非常感谢你的投稿，我们主编会尽快审核。:)
